const CardTypes = {
  ADD_TO_CARD: 'ADD_TO_CARD',
  REMOVE_FROM_CARD: 'REMOVE_FROM_CARD',
  CHANGE_COUNT: 'CHANGE_COUNT',
  INCREASE_COUNT: 'INCREASE_COUNT',
  DECREASE_COUNT: 'DECREASE_COUNT',
  CLEAR_CARD: 'CLEAR_CARD',
  PAY: 'PAY',
  GET_ADMIN_ORDER: 'GET_ADMIN_ORDER',
  GET_CUSTOMER_ORDER: 'GET_CUSTOMER_ORDER',
};

export default CardTypes;
