const ProductsTypes = {
  ADD_PRODUCT: 'ADD_PRODUCT',
  PUT_PRODUCT_LIST: 'PUT_PRODUCT_LIST',
  EDIT_PRODUCT: 'EDIT_PRODUCT',
  DELETE_PRODUCT: 'DELETE_PRODUCT',
  SAVE_PRODUCT: 'SAVE_PRODUCT',
  FETCH_PRODUCT: 'FETCH_PRODUCT',
};

export default ProductsTypes;
